main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predictor.urls')),
]

veriuser/urls.py
from django.urls import path
from . import views

app_name = 'veriuser'
urlpatterns = [
    path('Login/', views.login_page, name='login'),
    path('Sign-up/', views.create_user, name='create_user'),
    path('Logout/', views.logout_user, name='logout'),
    #path('Biodata/', views.biodata, name='bio'),
]

veriuser/models.py
from django.db import models
from django.contrib.auth.models import User

veriuser/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username',
                                                             'class':'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'user@email.com',
                                                             'class':'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'******',
                                                             'class':'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'******',
                                                             'class':'form-control'}))

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Confirm Password'
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'

class UserLoginForm(forms.Form):
    username = forms.ChoiceField(widget=forms.TextInput(attrs={'placeholder':'Username',
                                                               'class':'form-control'}))
    password = forms.ChoiceField(widget=forms.PasswordInput(attrs={'placeholder':'******',
                                                                   'class':'form-control'}))

veriuser/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, UserLoginForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def create_user(request):
    if request.user.is_authenticated:
        return redirect('veriuser:home')
    else:
        context = {}
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account Successfully created for ' + user )
                return redirect('veriuser:login')
            else:
                context['form'] = form
                context['error'] ='invalid input'
                return render(request, "create_user.html", context)
        else:
            form = CreateUserForm()
        context['form'] = form
        return render(request, "create_user.html", context)

def login_page(request):
    if request.user.is_authenticated:
        return redirect('allocator:home')
    else:
        if request.method == 'POST':
            form = UserLoginForm(request.POST)
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('main:home')
            else:
                context = {}
                context['form'] = UserLoginForm()
                messages.info(request, 'username or password is incorrect')
                return render(request, "login.html", context)

        context = {}
        context['form']=UserLoginForm()
        return render(request, "login.html", context)

def logout_user(request):
    logout(request,)
    return redirect('veriuser:login')

veriuser/templates/create_user.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="hh pb-5">
    <div class="container pt-5 hh">
        <div class="pt-5">
            <div class="card card-body">
                <div class="p-3 mt-5 bg-light">
                    <div class="">
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col col-md-6">
                                    <div class="form-group">{{form.first_name|as_crispy_field}}</div>
                                </div>
                                <div class="col col-md-6">
                                    <div class="form-group">{{form.last_name|as_crispy_field}}</div>
                                </div>
                            </div>
                            <div class="form-group">{{form.username|as_crispy_field}}</div>
                            <div class="form-group">{{form.email|as_crispy_field}}</div>
                            <div class="form-group">{{form.password1|as_crispy_field}}</div>
                            <div class="form-group">{{form.password2|as_crispy_field}}</div>
                            <input type="submit" value="Sign up" class="btn btn-dark btn-block">
                            <input type="reset" value="Clear" class="btn btn-info btn-block">
                            <a href="{% url 'veriuser:login' %}"><p class="text-center text-info">Allready have an
                                account</p></a>

                        </form>
                    </div>
                </div>
            </div>

        </div>
        <style>
    .hh {
        background: url({% static 'images/pexels-karolina-grabowska-4021775.jpg' %});
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        height: 100%;
        opacity: 0.90;
    }

    body {
        background: black;
    }

        </style>
        {% endblock content %}

veriuser/templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="hh pb-5">
    <div class="container pt-5 hh">
        <div class="pt-5">
            <div class="card card-body">
<div class="p-3 mt-5 bg-light">
    <div class="">
        <form method="POST" action="" autocomplete="off">
            {% csrf_token %}

                    {{form.username|as_crispy_field}}
                    {{form.password|as_crispy_field}}
            {% for message in messages %}
            <p class="text-primary">
               <b> {{message}} ! </b>
            </p>
            {% endfor %}
            <br>
            <input type="submit" value="Login" class="btn btn-dark btn-block">
            <input type="reset" value="Clear" class="btn btn-info btn-block">
            <a href="{% url 'veriuser:create_user' %}"><p class="text-center text-info">Sign up here if you don't have an account</p></a>
        </form>
</div>



            </div>
        </div>

</div>
<style>
    .hh {
        background: url({% static 'images/pexels-karolina-grabowska-4021775.jpg' %});
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover;
        height: 100%;
        opacity: 0.90;
    }

    body {
        background: black;
    }
</style>
{% endblock content %}